# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castroot',
            name='pod_id',
            field=models.IntegerField(default=1),
        ),
    ]
