# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_castroot_pod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='quote',
            field=models.CharField(default='', max_length=300),
        ),
    ]
