# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('podcast', '0004_episode_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='castroot',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='quote',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
