# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('podcast', '0005_auto_20161026_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('twitter_handle', models.CharField(default='', max_length=20)),
                ('blurb', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
