# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='epID',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
