# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_epid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='epID',
        ),
    ]
